
site_name: Knowledge Base
site_url: https://ssteinbuss.github.io/knowledge-base/
repo_url: https://github.com/ssteinbuss/knowledge-base
repo_name: knowledge-base
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
extra_css:
  - assets/styles.css
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - literate-nav:
      nav_file: SUMMARY.md

nav: literate-nav
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list

extra:
  generator: false